const TOGGLE_TODO = "TOGGLE_TODO";
const ADD_TODO = "ADD_TODO";
const DELETE_TODO = "DELETE_TODO";
const CLEAR_COMPLETED_TODOS = "CLEAR_COMPLETED_TODOS";

export { TOGGLE_TODO, ADD_TODO, DELETE_TODO, CLEAR_COMPLETED_TODOS };
